services:
  database-postgres:
    image: postgres:15
    container_name: database-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "1234:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/postgres:/docker-entrypoint-initdb.d
    networks:
      - dolynglish-network
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: dolynglish-backend
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PORT=${PORT}
      - HOST=${HOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - APP_KEY=${APP_KEY}
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
    ports:
      - "1235:3333"
    networks:
      - dolynglish-network
    depends_on:
      - database-postgres

volumes:
  postgres-data:

networks:
  dolynglish-network:
    driver: bridge
